name: Generar y Desplegar Sitio Semanalmente

on:
  schedule:
    # Se ejecuta automáticamente cada domingo a medianoche (UTC).
    - cron: '0 0 * * 0'
  # Permite la ejecución manual desde la pestaña "Actions" en GitHub.
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar el código del repositorio
        uses: actions/checkout@v3

      - name: 2. Configurar el entorno de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 3. Instalar las librerías necesarias
        run: |
          python -m pip install --upgrade pip
          pip install openai jinja2 python-dotenv

      - name: 4. Ejecutar el bot para crear los artículos
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py

      - name: 5. Publicar los nuevos archivos en Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy automático desde GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
